In [1]:
import numpy as np

In [2]:
#data matrix for pca

In [3]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
#mean of each column
M=np.mean(data.T,axis=1)
M

array([3., 4.])

In [6]:
#subtract the mean from data
scaled_data=data-M
scaled_data

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [7]:
#covariance Matrixs on scaled data
V=np.cov(scaled_data.T)
V

array([[4., 4.],
       [4., 4.]])

In [8]:
#eigen values and eigen vectors
values,vectors=np.linalg.eig(V)

In [9]:
#eigen values which is explained variance of components
values

array([8., 0.])

In [10]:
#eigen vectors which are principle components
vectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [11]:
vectors.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [12]:
scaled_data.T

array([[-2.,  0.,  2.],
       [-2.,  0.,  2.]])

In [13]:
#project the data/transform the data
p=vectors.T.dot(scaled_data.T)

In [14]:
p.T

array([[-2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.82842712,  0.        ]])

In [15]:
from sklearn.decomposition import PCA
pca=PCA()
pca.fit(data)


PCA()

In [16]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [17]:
pca.explained_variance_

array([8., 0.])

In [18]:
p=pca.transform(data)

In [19]:
p

array([[-2.82842712e+00, -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 2.82842712e+00,  2.22044605e-16]])