# SVD with numpy

In [2]:
import numpy as np

In [3]:
#data
A=np.array([[-1,2,0],[2,0,1],[0,-2,1]])
A

array([[-1,  2,  0],
       [ 2,  0,  1],
       [ 0, -2,  1]])

In [5]:
#U,s,VT
from numpy.linalg import svd
U,S,VT=svd(A)
print(U)
print(S)
print(VT)

[[-0.67028426 -0.14157742  0.72847433]
 [ 0.39926415 -0.89625169  0.19318659]
 [ 0.62554549  0.42034361  0.65727018]]
[3.15029268 2.05306258 0.92767992]
[[ 0.46624638 -0.8226726   0.32530617]
 [-0.80412841 -0.54739786 -0.23180398]
 [-0.36877068  0.15351016  0.91675668]]


In [7]:
sigma=np.zeros(A.shape)
sigma[:A.shape[0],:A.shape[0]]=np.diag(S)
sigma

array([[3.15029268, 0.        , 0.        ],
       [0.        , 2.05306258, 0.        ],
       [0.        , 0.        , 0.92767992]])

In [8]:
T=U.dot(sigma)
T=A.dot(VT.T)
T

array([[-2.11159159, -0.2906673 ,  0.67579101],
       [ 1.25779892, -1.8400608 ,  0.17921532],
       [ 1.97065138,  0.86299174,  0.60973635]])

# SVD using Scikit-learn
TruncatedSVD

In [9]:
from sklearn.decomposition import TruncatedSVD
svd=TruncatedSVD()
svd.fit(A)
T=svd.transform(A)
T

array([[ 2.11159159,  0.2906673 ],
       [-1.25779892,  1.8400608 ],
       [-1.97065138, -0.86299174]])

In [10]:
svd.singular_values_

array([3.15029268, 2.05306258])

# Randomized SVD

In [11]:
from sklearn.utils.extmath import randomized_svd

u,s,vt=randomized_svd(A,n_components=2)

print(u)
print(np.diag(s))
print(vt)

T=u.dot(np.diag(s))
T=A.dot(vt.T)
T

[[ 0.67028426  0.14157742]
 [-0.39926415  0.89625169]
 [-0.62554549 -0.42034361]]
[[3.15029268 0.        ]
 [0.         2.05306258]]
[[-0.46624638  0.8226726  -0.32530617]
 [ 0.80412841  0.54739786  0.23180398]]


array([[ 2.11159159,  0.2906673 ],
       [-1.25779892,  1.8400608 ],
       [-1.97065138, -0.86299174]])